# Test Colab

In [1]:
import numpy as np

In [2]:
import pdb

In [3]:
array_1d = np.arange(10)
print("1D array: ", array_1d)

1D array:  [0 1 2 3 4 5 6 7 8 9]


In [4]:
array_2d = np.arange(9).reshape(3, 3)
print("2D Array:\n", array_2d)

2D Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
array_3d = np.random.random((2, 2, 2))
print("3D Array:\n", array_3d)

3D Array:
 [[[0.32766574 0.16932346]
  [0.87055542 0.25086143]]

 [[0.69213842 0.35267948]
  [0.24979679 0.46560699]]]
